# generated by tools/generate.py — do not edit
REGIONS = [
    {"slug": 'spawn', "title": 'Welcome', "start_unlocked": True, "via": 'menu', "unlock_item": None},
    {"slug": 'thermal', "title": 'Thermal', "start_unlocked": False, "via": 'spawn', "unlock_item": 'Thermal Key'},
]
LOCATIONS = [
    {"slug": 'welcome_to_skyipelago', "name": 'Welcome to Skyipelago', "id": 87000001, "quest": '761701fd62993065', "region": 'spawn', "locked_item": None},
    {"slug": 'oak_log', "name": 'Oak Log', "id": 87000002, "quest": '036f39c4c7333d59', "region": 'spawn', "locked_item": None},
    {"slug": 'string', "name": 'String', "id": 87000003, "quest": '458b039503c8e217', "region": 'spawn', "locked_item": None},
    {"slug": 'string_mesh', "name": 'String Mesh', "id": 87000004, "quest": '34dd6f186a3e1ac7', "region": 'spawn', "locked_item": None},
    {"slug": 'cobblestone', "name": 'Cobblestone', "id": 87000005, "quest": '23111bcb1eb5da69', "region": 'spawn', "locked_item": None},
    {"slug": 'stone_hammer', "name": 'Stone Hammer', "id": 87000006, "quest": '07442e493b9c5306', "region": 'spawn', "locked_item": None},
    {"slug": 'hammer_time_but_more', "name": 'Hammer Time but More', "id": 87000007, "quest": '53905fea998dfbb4', "region": 'spawn', "locked_item": None},
    {"slug": 'gravel_sand_and_dust', "name": 'Gravel, Sand, and Dust', "id": 87000008, "quest": '248d41594d787960', "region": 'spawn', "locked_item": None},
    {"slug": 'compressed_gravel_sand_and_dust', "name": 'Compressed Gravel, Sand, and Dust', "id": 87000009, "quest": '2e87d640d3ec75fb', "region": 'spawn', "locked_item": None},
    {"slug": 'oak_sieve', "name": 'Oak Sieve', "id": 87000010, "quest": '0a1a02bf33b8135e', "region": 'spawn', "locked_item": None},
    {"slug": 'oak_compressed_sieve', "name": 'Oak Compressed Sieve', "id": 87000011, "quest": '39bbfd11affe24a5', "region": 'spawn', "locked_item": None},
    {"slug": 'enter_thermal', "name": 'Enter Thermal', "id": 87000012, "quest": '0000000087020001', "region": 'thermal', "locked_item": None},
]
ITEMS = [
    {"slug": 'thermal_key', "name": 'Thermal Key', "id": 87100001, "classification": 'progression', "event": False},
    {"slug": 'gold_ingot_1', "name": 'Gold Ingot 1', "id": 87100002, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_2', "name": 'Gold Ingot 2', "id": 87100003, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_3', "name": 'Gold Ingot 3', "id": 87100004, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_4', "name": 'Gold Ingot 4', "id": 87100005, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_5', "name": 'Gold Ingot 5', "id": 87100006, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_6', "name": 'Gold Ingot 6', "id": 87100007, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_7', "name": 'Gold Ingot 7', "id": 87100008, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_8', "name": 'Gold Ingot 8', "id": 87100009, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_9', "name": 'Gold Ingot 9', "id": 87100010, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_10', "name": 'Gold Ingot 10', "id": 87100011, "classification": 'filler', "event": False},
    {"slug": 'gold_ingot_11', "name": 'Gold Ingot 11', "id": 87100012, "classification": 'filler', "event": False},
]
